// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gmbfybfvlpgvhwydbsft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtYmZ5YmZ2bHBndmh3eWRic2Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NDE2NDYsImV4cCI6MjA3MzMxNzY0Nn0.qgr1Ey7twEwdYVBJoc951aMR_3IibBTdL6W5h9ZXpDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);